on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Generate SBOM
      uses: CycloneDX/gh-gomod-generate-sbom@v2
      with:
        version: v1
        args: mod -licenses -json -output bom.json

    - name: Upload SBOM as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SBOM
        path: bom.json

    - name: Commit SBOM to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add bom.json
        git commit -m "Update SBOM" || echo "No changes to commit"
        git push
